---
- name: Install GitLab
  hosts: localhost
  become: true

  tasks:
    - name: Installing Dependencies & Postfix
      apt:
        name:
        - apt-transport-https
        - ufw
        - ca-certificates
        - curl 
        - openssh-server
        state: present
      become: yes       

    - name: Installing Postfix
      apt:
        name=postfix
        state=latest 
        update_cache=yes
      become: yes 


    - name: Run ufw allow OpenSSH script 
      command: ufw allow OpenSSH
    - name: Run ufw allow http script 
      command: ufw allow http
    - name: Run ufw allow https script 
      command: ufw allow https
    - name: Run ufw allow postfix script 
      command: ufw allow postfix

    - name: Install GitLab repository
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: 0777
    
    - name: Run GitLab repository script
      shell: /tmp/script.deb.sh

    - name: Install GitLab CE
      apt:
        name=gitlab-ce
        state=latest 
        update_cache=yes
      become: yes 